

-- INSERT INTO USER (ID, LOGIN_ID, PASSWORD, NICKNAME, ACTIVATED, EMAIL, NAME, COLLEGE_CODE, MAJOR_CODE, STUDENT_NUM, EMAIL_AUTHENTICATION, DELETED) VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 1, '11111@naver.com', '어드민', '001', 'm001', 32210311, FALSE, FALSE);
-- 비번? "$2a$10$nicQMhS9JcPhrd3E/gc8gOHran0UsHvcIjfUUu9qGA.xD4rbaXbG2"
-- 서버 실행과 동시에 실행되는 상황.
INSERT INTO user (ID, LOGIN_ID, PASSWORD, NICKNAME, COLLEGE_CODE, MAJOR_CODE, ACTIVATED, EMAIL_AUTHENTICATION, DELETED, DEVICE_TOKEN) VALUES (1, 'admin', '$2a$10$JwoSm1YVIbuY8u1WIS.XMu/G4npvQv60jAzIlu4WcnXIPuEBJz5.C', 'admin', 0, 0, TRUE, FALSE, FALSE, 'sampledevicetoken');
INSERT INTO user (ID, LOGIN_ID, PASSWORD, NICKNAME, COLLEGE_CODE, MAJOR_CODE, ACTIVATED, EMAIL_AUTHENTICATION, DELETED, DEVICE_TOKEN) VALUES (2, 'user1', '$2a$10$16DPpdNdw6BJb48NDYswpunHe5vs3ptZkKNLrKO80eAARLiCZ3We2', '가나초코릿', 0, 0, TRUE, FALSE, FALSE, 'sampledevicetoken');
INSERT INTO user (ID, LOGIN_ID, PASSWORD, NICKNAME, COLLEGE_CODE, MAJOR_CODE, ACTIVATED, EMAIL_AUTHENTICATION, DELETED, DEVICE_TOKEN) VALUES (3, 'user2', '$2a$10$16DPpdNdw6BJb48NDYswpunHe5vs3ptZkKNLrKO80eAARLiCZ3We2', '나는나비', 1, 1, TRUE, FALSE, FALSE, 'sampledevicetoken');
INSERT INTO user (ID, LOGIN_ID, PASSWORD, NICKNAME, COLLEGE_CODE, MAJOR_CODE, ACTIVATED, EMAIL_AUTHENTICATION, DELETED, DEVICE_TOKEN) VALUES (4, 'user3', '$2a$10$16DPpdNdw6BJb48NDYswpunHe5vs3ptZkKNLrKO80eAARLiCZ3We2', '다람쥐ㅋ', 2, 2, TRUE, FALSE, FALSE, 'sampledevicetoken');

INSERT INTO authority (AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO authority (AUTHORITY_NAME) values ('ROLE_ADMIN');

INSERT INTO user_authority (USER_ID, AUTHORITY_NAME) values (1, 'ROLE_USER');
INSERT INTO user_authority (USER_ID, AUTHORITY_NAME) values (1, 'ROLE_ADMIN');
INSERT INTO user_authority (USER_ID, AUTHORITY_NAME) values (2, 'ROLE_USER');
INSERT INTO user_authority (USER_ID, AUTHORITY_NAME) values (3, 'ROLE_USER');
INSERT INTO user_authority (USER_ID, AUTHORITY_NAME) values (4, 'ROLE_USER');

-- friend 신청(user1이 user2에게 신청)
INSERT INTO friend (ID, STATUS, RECIPIENT_ID, REQUESTOR_ID) values (1, 1, 3, 2); -- 2->3
INSERT INTO friend (ID, STATUS, RECIPIENT_ID, REQUESTOR_ID) values (2, 1, 2, 4); -- 4->2

-- user1,2 사진 추가
INSERT INTO user_picture (ID, STORED_FILE_PATH, USER_ID) values (1, 'https://d1cy8kjxuu1lsp.cloudfront.net/2022/user/20220504/a43e5a59-3b08-4fac-9c36-27468edc11da83851993430251user1.jpg', 2);
INSERT INTO user_picture (ID, STORED_FILE_PATH, USER_ID) values (2, 'https://d1cy8kjxuu1lsp.cloudfront.net/2022/user/20220504/a43e5a59-3b08-4fac-9c36-27468edc11da83851993430251user2.jpg', 3);
INSERT INTO user_picture (ID, STORED_FILE_PATH, USER_ID) values (3, 'https://d1cy8kjxuu1lsp.cloudfront.net/2022/user/20220504/a43e5a59-3b08-4fac-9c36-27468edc11da83851993430251user3.jpg', 4);

-- Interest 생성
INSERT INTO interest (ID, INTEREST_CODE) values (1, 0);
INSERT INTO interest (ID, INTEREST_CODE) values (2, 1);
INSERT INTO interest (ID, INTEREST_CODE) values (3, 2);
INSERT INTO interest (ID, INTEREST_CODE) values (4, 3);
INSERT INTO interest (ID, INTEREST_CODE) values (5, 4);
INSERT INTO interest (ID, INTEREST_CODE) values (6, 5);
INSERT INTO interest (ID, INTEREST_CODE) values (7, 6);
INSERT INTO interest (ID, INTEREST_CODE) values (8, 7);
INSERT INTO interest (ID, INTEREST_CODE) values (9, 8);
INSERT INTO interest (ID, INTEREST_CODE) values (10, 9);
INSERT INTO interest (ID, INTEREST_CODE) values (11, 10);
INSERT INTO interest (ID, INTEREST_CODE) values (12, 11);
INSERT INTO interest (ID, INTEREST_CODE) values (13, 12);
INSERT INTO interest (ID, INTEREST_CODE) values (14, 13);
INSERT INTO interest (ID, INTEREST_CODE) values (15, 14);
INSERT INTO interest (ID, INTEREST_CODE) values (16, 15);
-- CREATEAT(필요하면): 2022-05-03 20:40:15.943059
